### ISSUE TITLE
Add NumPy interface for generating primes

### ISSUE THREAD

**Issue by pstoll** [hickford/primesieve-python#13]
I've implemented a numpy integration, i.e. generate primes directly into preallocated numpy arrays.

It requires a change in interface to the primesieve library. I've submitted an issue there for that:

https://github.com/kimwalisch/primesieve/issues/17

This issue is for the python side of integrating it. Again, I've got this implemented and running.

It helps scaling in generating sequences of primes for length 10**9, where the underlying implementation seems to bog down. Also, having a numpy integration helps cutout another copy of the data.

**Comment by tsgallion** [comment]
I think it's awesome you can dive deep like this.  Good work!  




Sent via the Samsung Galaxy Note® 3, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by pstoll** [comment]
Long discussion and some performance benchmarking in the issue over in https://github.com/kimwalisch/primesieve/issues/17

Short version is - the current conversion that primesieve.pyx uses to convert std:vector to output types adds a ton of overhead.

**Comment by kimwalisch** [comment]
I am interested in supporting Numpy in primesieve-python so I will give it a try.

My idea is to conditionally build the ```primesieve.numpy``` submodule if numpy is installed and implement the numpy support using the ideas described here: https://github.com/kimwalisch/primesieve/issues/17#issuecomment-157677940. This solution will give us native C/C++ performance for storing primes in an array, this is about 10 times faster than the current ```generate_primes()``` and ```generate_n_primes()``` functions.

I found the [Biopython](https://github.com/biopython/biopython) project which checks whether numpy is installed in their ```setup.py``` and if yes, builds a submodule which depends on numpy. I want to reuse their code:

```python
# setup.py

def is_pypy():
    import platform
    try:
        if platform.python_implementation() == 'PyPy':
            return True
    except AttributeError:
        # New in Python 2.6, not in Jython yet either
        pass
    return False

def can_import(module_name):
    """can_import(module_name) -> module or None"""
    try:
        return __import__(module_name)
    except ImportError:
        return None

def is_Numpy_installed():
    if is_pypy():
        return False
    return bool(can_import("numpy"))

# Add extensions that requires NumPy to build
if is_Numpy_installed():
    import numpy
    numpy_include_dir = numpy.get_include()
    EXTENSIONS.append(
        Extension('Bio.Cluster.cluster',
                  ['Bio/Cluster/clustermodule.c',
                   'Bio/Cluster/cluster.c'],
                  include_dirs=[numpy_include_dir],
                  ))
```

I will create a new ```NumPy``` branch shortly and start working on this. Any help and/or feedback is welcome.

**Comment by pstoll** [comment]
@kimwalisch - sorry, i just saw your comment on this issue. I created a branch that does something slightly different. It  does the generate_n_primes_numpy & generate_n_primes_numpy versions.

I ended up using the iterator approach for generating_n_primes. and the other approach for  generate_primes. 

There is a good reason to allow the caller to specify the array but it requires a longer explanation that I can do tonight. :)

Here is the branch for you to look at:
  https://github.com/pstoll/primesieve-python/tree/add-numpy-support-iterators

I don't expect that particular code to merge necessarily but I wanted to get something out here to discuss.

**Comment by kimwalisch** [comment]
> There is a good reason to allow the caller to specify the array but it requires a longer explanation that I can do tonight. :)

I be really interested in hearing your thoughts about this, because currently I cannot see the need for such functionality. There is one issue I am aware of which could possibly cause issues when implementing my idea of binding a C primes array to a numpy array without copying: When you allocate memory in C/C++ it must be deallocated using the same allocator. So my idea will only work if primesieve and numpy (Cypthon or CPython) use the same allocator as we will allocate memory in primesieve and deallocate that memory in numpy (Cypthon or CPython). But as far as I can see this is the case because on Unix-like operating systems all C programs/libraries use the malloc allocator from the libc library.

**Comment by hickford** [comment]
Plan sounds sensible to me. Agree numpy should be optional—because the dependency would be disproportionate for a little library, and it can be awkward to install on Windows (I took care to make `pip install primesieve` work reliably on all computers).

**Comment by kimwalisch** [comment]
Good new everybody: I got the new ```primesieve.numpy``` module working!

I had to rename the old ```primesieve``` extension to ```primesieve.core``` and introduce a ```__init__.py``` file which imports everything from ```primesieve.core```. This was necessary because ```primesieve``` must now be a package instead of a module (extension).

Currently ```primesieve.numpy``` is just a copy of ```primesieve.core```. I plan to implement the new numpy ```generate_primes()``` functions on the weekend.

@hickford What is the git command for changing ```lib/primesieve``` (which seems to be a link to https://github.com/kimwalisch/primesieve/tree/v5.5.0) to point to https://github.com/kimwalisch/primesieve/tree/malloc?

**Comment by pstoll** [comment]
I think just compiling in the numpy versions conditionally and including them in the normal primeseive module is probably adequate and it is going to be much simpler and easier to maintain I think.

Ok, now that you are threatening to implement the numpy inteface, let me state the case for allowing the caller to specify the array vs  having primesieve do the memory allocation. While this may seem very  numpy specific, I think it applies in general to uses of numeric c libraries.

By letting the caller specify the output array, that lets you do two things:
* avoid extra memory e.g. for copies of outputs. For many numeric computations you want to control extra copies of arrays;
* the caller can send in a slice of an existing array. This is magic and cool.

As an example, let's say you create a 1d array that is 2*N elements long. And for whatever reason, I want to have the generate_primes write its data into every other elements. Easy if you let the caller specify the output array.

```python
import primesieve as ps
import numpy as np

n = 10**6

# store the primes into the array a starting at position 0
a = np.zeros( (n,), dtype=np.uint64)
ps.generate_n_primes_numpy( n, out=a)
print("straight into array:", a[0:20])

# store the primes in array a but offset 10 locations in
a = np.zeros( (2*n,), dtype=np.uint64)
b = ps.generate_n_primes_numpy( n, out=a[10::])
print("offset by 10:", a[0:20])

# store the primes into array a but every other location via an 
a = np.zeros( (2*n,), dtype=np.uint64)
b = ps.generate_n_primes_numpy( n, out=a[::2])
print("strided by 2:", a[0:20])
```

which results in:

```bash
primesieve-python pstoll$ python testnumpy.py
straight into array: [ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71]
offset by 10: [ 0  0  0  0  0  0  0  0  0  0  2  3  5  7 11 13 17 19 23 29]
strided by 2: [ 2  0  3  0  5  0  7  0 11  0 13  0 17  0 19  0 23  0 29  0]
```
This extends to indexing into higher dimensional arrays, too. Is it strictly necessary for generating primes? Probably not. Is it a small thing to do and feel more numpy-ish? I think so.

There is a general notion in NumPy known as ufuncs. (universal functions). They always let you specify the output array, which is part of the general gestalt of letting the caller optimize (or not).

Here are some reference docs, in particular learn I'd suggest you read about. While we are not quite doing all the ufunc functionality (e.g. honoring the output array types) the notion of letting the caller specify the output is pretty standard.

I'd start with this one:
* http://docs.scipy.org/doc/numpy-dev/reference/internals.code-explanations.html

And then if you want more info go over these:
* http://docs.scipy.org/doc/numpy/user/c-info.how-to-extend.html
* http://docs.scipy.org/doc/numpy/user/c-info.ufunc-tutorial.html
* http://docs.scipy.org/doc/numpy/reference/ufuncs.html
* http://docs.scipy.org/doc/numpy/reference/c-api.array.html

I still agree that the general case of generate_primes(a,b) not knowing its output size is a real issue. In this case, I just gave up and just called the basic version, getting a std:vector back and efficiently copying it into the output array. I guess in this case perhaps it does make sense to create the NumPy array directly from the underlying memory allocated by primesieve.

In this case, it is worth reading this entry, although I think we can do this easily in Cython now: http://blog.enthought.com/python/numpy-arrays-with-pre-allocated-memory/

**Comment by kimwalisch** [comment]
@pstoll Thanks for your detailed feedback!

I am aware that it would be very useful to specify the array in some cases vs having primesieve do the memory allocation. But lets face it: in 99% percent of the time the user simply wants to generate an array of primes for use in his program (what about your program?!). Hence I want to make primesieve-python as simple to use as possible for that use case.

My second argument against specifying the array is that I want to have a clean C/C++ API. This is very important to me, and allowing the user to specify his own array would require to add new error prone functions to primesieve's C/C++ API which I would only consider doing if there was no other solution available.

Based on your comments I might support specifying the integer type of the primes array just like in primesieve's C API.

**Comment by kimwalisch** [comment]
Good news again, it works!

```python
$ python
>>> from primesieve.numpy import *
>>> generate_primes(100)
array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])
>>> generate_n_primes(100)
array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239,
       241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
       317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397,
       401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467,
       479, 487, 491, 499, 503, 509, 521, 523, 541])
>>> 
```

And here is some benchmarking code:

```python
def primesieve_numpy():
    sz = 10**8
    import primesieve.numpy as ps
    a = ps.generate_n_primes(sz)
    return a

def primesieve_python():
    sz = 10**8
    import primesieve as ps
    a = ps.generate_n_primes(sz,1)
    return a

def benchmark():
    import timeit
    num = 5
    print("primesieve_numpy() : ", timeit.timeit("primesieve_numpy()", setup="from __main__ import primesieve_numpy", number=num))
    print("primesieve_python(): ", timeit.timeit("primesieve_python()", setup="from __main__ import primesieve_python", number=num))
    
if __name__ == '__main__':
    benchmark()
```

The results:

```
$ python benchmark.py
('primesieve_numpy() : ', 6.2922890186309814)
('primesieve_python(): ', 40.99750590324402)
```

Using the new ```primesieve.numpy``` package we can generate an array of primes using native C/C++ performance!

There was one issue with the file name ```numpy.pyx``` which failed to compile because of a name clash with the ```numpy``` library. So I have renamed ```numpy.pyx``` to ```primesieve/numpy/core.pyx```.

**Question:** What would be a better, more pythonic file name for  ```core.pyx``` (I already use that file name twice ```primesieve/core.pyx``` and ```primesieve/numpy/core.pyx```). Is e.g. ```_numpy.pyx``` or ```numpy_.pyx``` a good choice?

**Comment by pstoll** [comment]
@kimwalisch - Good work. 

But...let me make the case again for different names for the two versions - i.e. the functions that return lists and functions that return numpy arrays.

i.e. generate_primes_numpy() and generate_n_primes_numpy()

I think having the functions called the same thing but vary based on which module they come out of feels a little ... odd. 

It will be simpler to maintain the 

Looking at the Biopython setup, note that they aren't including a sub-package named "numpy" so much as conditionally compiling modules like kdtrees, cluster.c, etc. Another package to look towards is GDAL, which offers optional NumPy bindings:
  https://pypi.python.org/pypi/GDAL/
and the source:
  http://trac.osgeo.org/gdal/browser/trunk/gdal/swig/python?order=name#extensions

Also note that GDAL let's the caller pass in the output array ;)   
  http://trac.osgeo.org/gdal/browser/trunk/gdal/swig/python/osgeo/gdal_array.py#L223

Also, naming something "numpy" just feels... risky. if someone careless does something like this:

````
import numpy
from primeseive import *
```
they may accidentally import the symbol  "numpy" into their namespace, hiding the previously imported version. 

Lastly, the primesieve.numpy module isn't going to provide all functions, right? Just the ones that return sequences of primes? So folks will still need to access the functions inside primeseive?

**Comment by kimwalisch** [comment]
> they may accidentally import the symbol "numpy" into their namespace, hiding the previously imported version.

I see your point, thanks for the feedback. I also like your alternative suggestion:

```
generate_primes_numpy()
generate_n_primes_numpy()
```

Another good option would be:

```
generate_primes_array()
generate_n_primes_array()
```

I will change the code to one of the alternatives above tomorrow.

**Comment by kimwalisch** [comment]
> Looking at the Biopython setup, note that they aren't including a sub-package named "numpy" so much as conditionally compiling modules like kdtrees, cluster.c, etc.

```python
# Biopython setup.py

if is_Numpy_installed():
    import numpy
    numpy_include_dir = numpy.get_include()
    EXTENSIONS.append(
        Extension('Bio.Cluster.cluster',
                  ['Bio/Cluster/clustermodule.c',
                   'Bio/Cluster/cluster.c'],
                  include_dirs=[numpy_include_dir],
                  ))
    EXTENSIONS.append(
        Extension('Bio.KDTree._CKDTree',
                  ["Bio/KDTree/KDTree.c",
                   "Bio/KDTree/KDTreemodule.c"],
                  include_dirs=[numpy_include_dir],
                  ))
    EXTENSIONS.append(
        Extension('Bio.motifs._pwm',
                  ["Bio/motifs/_pwm.c"],
                  include_dirs=[numpy_include_dir],
                  ))
    EXTENSIONS.append(
        Extension('Bio.PDB.QCPSuperimposer.qcprotmodule',
                  ["Bio/PDB/QCPSuperimposer/qcprotmodule.c"],
                  include_dirs=[numpy_include_dir],
                  ))
```

I think I must put the primesieve numpy functions in a different package (or module) just as Biopython does above (and what I am currently doing with primesieve.numpy). Just imagine ```generate_primes_numpy()``` was part of the ```primesieve``` module: if the user installs primesieve-python using:

```python
$ pip install primesieve
$ python
# Will crash if generate_primes_numpy() is located in primesieve module
# and numpy is not installed
>>> import primesieve
```

Now the question is whether it is a good choice to put ```generate_primes_numpy()``` in e.g. ```primesieve._numpy``` and then conditionally import it into the ```primesieve``` module e.g.:

```python
# file: primesieve/__init__.py

def is_pypy():
    try:
        if platform.python_implementation() == 'PyPy':
            return True
    except AttributeError:
        pass
    return False

def can_import(module_name):
    """can_import(module_name) -> module or None"""
    try:
        return __import__(module_name)
    except ImportError:
        return None

def is_Numpy_installed():
    if is_pypy():
        return False
    return bool(can_import("numpy"))

if is_Numpy_installed():
    global primesieve._numpy.generate_primes_numpy
    global primesieve._numpy.generate_n_primes_numpy
    import primesieve._numpy.generate_primes_numpy
    import primesieve._numpy.generate_n_primes_numpy
```

The problem I see with this approach is that the ```generate_primes_numpy()``` function will magically be undefined if numpy is not installed:

```python
>>> from primesieve import *
>>> generate_primes_numpy(100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'generate_primes_numpy' is not defined
>>> 
```

What's your opinion on these issues? Do you have a good suggestion?

**Comment by kimwalisch** [comment]
Based on @pstoll comments I have finally decided to use the following naming:

```python 
>>> from primesieve.numpy import *

# Generate a numpy array with the primes below 100
>>> generate_primes_array(100)
array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

# Generate a numpy array with the first 100 primes
>>> generate_n_primes_array(100)
array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239,
       241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
       317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397,
       401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467,
       479, 487, 491, 499, 503, 509, 521, 523, 541])
```

I like it a lot, it is obvious for the user that this functionality requires numpy. Also there won't be any name clashes if the user imports both ```primesieve``` and ```primesieve.numpy``` and the numpy functionality is separated from the main ```primesieve``` module so users which have not installed numpy can still use it.

> Also, naming something "numpy" just feels... risky. if someone careless does something like this:

```python
import numpy
from primeseive import *
from primeseive.numpy import *
```

I have tested this and it works without any issue. (I think the reason why it is not an issue is because both ```primesieve``` and ```primesieve.numpy``` are actually packages).

**Comment by pstoll** [comment]
Looks good to me! 

To answer one of your questions - the availability of the numpy/array version of the function is dependent on numpy being available when the module is installed. You can checkout the branch I rerenced above to see how to conditionally compile those functions in Cython.

Even with the current approach, callers who want the numpy versions but want to allow degrading nicely to the list based methods will need to do a runtime check for the existing of a functions. this isn't terrible and is a relatively normal path in python, e.g.

```python
has_numpy_primesieve = False
generate_primes_func = ps.generate_primes
try:
    import primeseive.numpy
    has_numpy_primesieve = True
    generate_primes_func = primesieve.numpy.generate_primes_array
except:
    pass

primes = generate_primes_func(1,10**8) # primes is a sequence, either a list or a numpy array
```

Is a way to check at runtime whether or not numpy is available.
