### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by hickford** [hickford/primesieve-python#2]
Publish package to PyPI at https://pypi.python.org/pypi/primesieve

Alas chapter in Python packaging guide about C extensions hasn't been written yet https://packaging.python.org/en/latest/extensions.html

It's important package installs on Windows computers without a C compiler, this probably means publishing a binary wheel http://pythonwheels.com/

Cython also recommends distributing the generate `.c` files http://docs.cython.org/src/reference/compilation.html#distributing-cython-modules

**Comment by hickford** [comment]
The difficulty is the manual step "Build and install primesieve `cd lib/primesieve && ./autogen.sh && ./configure && make && make install`" that right now you have to do before `python setup.py install`

**Comment by kimwalisch** [comment]
I am currently on holiday. I will start contributing once I am back home on the 11th July.

Greetings,
Kim

**Comment by hickford** [comment]
Cool. There's scant documentation about it, but it looks like `distutils.command.build_clib` might be useful

https://stackoverflow.com/questions/16854066/using-distutils-and-build-clib-to-build-c-library

**Comment by hickford** [comment]
Published.

https://pypi.python.org/pypi/primesieve
