### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by brl0** [hickford/primesieve-python#31]
I have found a minor issue (unrelated to this pull request) yesterday while reviewing your code changes. We have switched all functions to use the C API instead of the C++ API for performance reasons. However when the primesieve C API is used we need to check ```errno``` after each call into libprimesieve to know whether an error has occured. We correctly do this for ```primesieve.primes(n)``` and ```primesieve.n_primes(n)```. However for all other functions we don't do it. This means that in case an error occurs for e.g. ```primesieve.count_prime(n)``` that function will silently return an incorrect result.

The reason for this issue is that C does not support C++ exceptions. When an error occurs inside libprimesieve an exception (which contains a message of what went wrong) is thrown. However in the libprimesieve C API all exceptions are caught (inside libprimesieve) and errno is set instead.

> Along these lines, based on some quick testing, it seems the C interface is noticeably faster than the C++ interface. To test, I created another submodule based on the array submodule, and modified it to include the C++ interface rather than C. The performance matched very closely with the base module, with the array submodule based on the C interface performing much better.

Is my understand right that you only measured a speed up when using the C API for ```primesieve.primes(n)``` and ```primesieve.n_primes(n)```. If so I suggest that we switch back all other functions to the C++ API because there error handling works out of the box.

_Originally posted by @kimwalisch in https://github.com/hickford/primesieve-python/pull/30#issuecomment-556978990_

**Comment by brl0** [comment]
I figured a separate issue would be better for an ongoing discussion on this issue.

As noted in the other thread, running count_primes and count_twins in the C version is about 3x faster than in the C++ version.

**Comment by kimwalisch** [comment]
OK, let me benchmark this as well. If there is really a 3x speedup we will use the C API with proper error handling.

**Comment by kimwalisch** [comment]
I have now benchmarked primesieve-python-1.4.4 which uses the C++ API vs primesieve-python-2.0.0 which uses the C API on Ubuntu 18.04 x64 using the following benchmark:

```python
"""Tests for primesieve module."""

import primesieve

def test_count_primes():
    """Test count_primes function."""
    assert primesieve.count_primes(100) == 25
    assert primesieve.count_primes(10**6) == 78498
    assert primesieve.count_primes(100, 10**6) == 78473
    primesieve.count_primes(10**10)
    assert primesieve.count_primes(10**9, 10**10) == 404204977

    for x in range(10000000, 10003000):
        primesieve.count_twins(x)

    for x in range(0, 300000):
        primesieve.count_primes(x)

def test_nth_prime():
    """Test nth prime function."""
    assert primesieve.nth_prime(25) == 97
    assert primesieve.nth_prime(26) == 101
    assert primesieve.nth_prime(1, 100) == 101
    assert primesieve.nth_prime(100, 1000000) == 1001311
    primesieve.nth_prime(10**9)
```

This code does a few large computations but also many tiny computations, so it is a good mix.

Timings are:

* primesieve-python-1.4.4: 8.96 seconds
* primesieve-python-2.0.0: 7.54 seconds

So using the C API indeed is a bit faster but not 3x. And if we add proper error handling to the C API this will also incur a small slowdown in which case there would not be much benefit in using the C API. I can understand that using the C API for the primesieve.primes(n) and the primesieve.n_primes(n) functions provides a significant speedup as this allows us to avoid converting the C primes array into a python list (which is very slow). However the other functions just return a single integer and hence from my understanding this should perform similarly for the C and C++ APIs.

Can you please let me know what code you have used for your benchmark and also the operating system you have used? For your information: the OpenMP multi-threading of primesieve-python-1.4.4 does not work on macOS and possibly also not on Windows. However the new C++11 multi-threading works on all operating systems. Maybe this could explain the huge performance speedup you have measured? Note that multi-threading is used only for the count functions and the nth_prime function.

**Comment by brl0** [comment]
I am running on Windows 10, python 3.7.5.
I ran the following at the IPython prompt.  I saw nearly identical performance for count_twins.

```
# version 2
%timeit count_primes(1e9)
68.8 ms ± 1.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

# version 1.4.4
%timeit ps.count_primes(1e9)
186 ms ± 7.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by kimwalisch** [comment]
OK, you measured a nearly 3x speedup. Can you please run the same benchmark but with 1e12 instead of 1e9. And while the benchmark is running have a look at the CPUs in the Windows Task Manager. I think that version 2 uses multi-threading while version 1.4.4 does not use multi-threading.

After thinking about it I even think that the 30% performance speedup I measured are most likely related to libprimesieve improvements and not because the C API is faster than the C++ API for counting primes and the nth_prime function.

The reason why I would prefer to use the C++ API (if there is not much performance difference) is that the error messages are better. Using the C API we can just report that an error occurred while using the C++ API you get detailed error info. Also we don't need to implement error handling for the C++ API.

**Comment by brl0** [comment]
Further testing has proven your point.  Using the C++ interface and a more recent version of primesieve performed about as well as the C API.  I have submitted a [PR](https://github.com/hickford/primesieve-python/pull/32) to make the change back to the C++ API.

**Comment by kimwalisch** [comment]
Fixed by https://github.com/hickford/primesieve-python/pull/32
