### ISSUE TITLE
Updated conda-forge feedstock

### ISSUE THREAD

**Issue by brl0** [hickford/primesieve-python#34]
I updated the feedstock for conda-forge, and the update has passed all checks.  Are you able to review/accept the [PR (#16)](https://github.com/conda-forge/python-primesieve-feedstock/pull/16)?  

Also, the installation instructions indicate this package can be installed on python 3, but it can only be installed on python>=3.5.  It might be a good idea to indicate the minimum python (3.5) for the current version.
I can understand not wanting to include specific instructions for rarely used older versions: python 3.4 (which should work with 1.4.4), and python 3.3 (which should work with 1.3.0).  I had previously added those just for consistency with the instructions for python 2.7, but that version is much more common.

Anyway, thanks again for the great package and for being great to work with.  I really appreciate it.

**Comment by kimwalisch** [comment]
Thanks, merged!
