### ISSUE TITLE
Support Python 2.7 on Windows

### ISSUE THREAD

**Issue by hickford** [hickford/primesieve-python#8]
Building on Windows for Python 2.7 using msvc fails with an error about missing `stdint.h`

**Comment by hickford** [comment]
You can fix this by adding the `msvc_compat` folder to includes (as I did in the windows branch), but this breaks builds with other compilers.

**Comment by hickford** [comment]
Possible solutions:

1. Complex automatic switching logic in setup.py (it seems to be surprisingly difficult to work out what compiler is being used)
2. Add a manual option to setup.py and explain it in the install instructions

**Comment by hickford** [comment]
The good news is once binary wheels are published to PyPI, pip installs will use those (no compilation necessary).

Most Python users on Windows don't have a working compiler anyway https://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat

**Comment by kimwalisch** [comment]
> Building on Windows for Python 2.7 using msvc fails with an error about missing stdint.h

The problem is due to an old compiler version, I guess you used MSVC 2010? Microsoft only supports stdint.h since MSVC 2012 or 2013. Based on your comments I would do nothing at all as there will probably be very few users that build on Windows using an old compiler.

**Comment by hickford** [comment]
If only! To build extensions the msvc has to match the version used to build the Python binaries. For Python 2.7 this is Visual C++ 2010 [1]. A sizeable part of the community still use Python 2.7

I think I'll put a manual workaround in appveyor.yml that builds the wheels and publish those.

[1] https://stackoverflow.com/questions/2676763/what-version-of-visual-studio-is-python-on-my-computer-compiled-with

**Comment by hickford** [comment]
Attempt at 1 in python27 branch

**Comment by hickford** [comment]
Fixed by https://github.com/hickford/primesieve-python/commit/dd430e214e0d467409e7ee1b8b66a861011956ab 

Published wheels to https://pypi.python.org/pypi/primesieve
